import { Product } from './firestore';

export const SEED_PRODUCTS: Omit<Product, 'id'>[] = [
  {
    slug: 'biometric-access-control',
    name: 'Biometric Access Control System',
    category: 'Access Control',
    tag: 'Most Popular',
    shortDesc: 'Fingerprint, facial recognition, and card-based access for estates, offices, and residences.',
    longDesc: 'Our biometric access control systems combine fingerprint scanning, facial recognition, and smart card/fob technology into a single unified platform.',
    price: 'From ₦350,000',
    priceNote: 'Installation inclusive. Final quote after site survey.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80'],
    features: ['Fingerprint & facial recognition', 'Smart card / fob integration', 'Visitor management log', 'Remote access management'],
    specs: [{ label: 'Recognition speed', value: '< 0.5 seconds' }, { label: 'User capacity', value: 'Up to 10,000' }],
    useCases: ['Gated residential estates', 'Corporate offices', 'Schools'],
    faqs: [{ q: 'Does it work during power outage?', a: 'Yes, battery backup for 8 hours.' }],
    relatedSlugs: ['remote-gate-system', 'video-intercom'],
    inStock: true, isVisible: true, order: 1,
  },
  {
    slug: 'cctv-surveillance',
    name: 'CCTV & Surveillance System',
    category: 'CCTV & Surveillance',
    shortDesc: 'HD and 4K cameras with night vision, motion detection, and remote live-view.',
    longDesc: 'From single-property installations to multi-site estate deployments, our CCTV systems use Tier 1 HD and 4K cameras.',
    price: 'From ₦180,000',
    priceNote: '4-camera starter package.',
    image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&q=80'],
    features: ['HD / 4K resolution cameras', 'Infrared night vision up to 40m', 'AI motion detection', 'Mobile live-view app'],
    specs: [{ label: 'Resolution', value: '2MP – 8MP (4K)' }],
    useCases: ['Residential homes', 'Retail shops', 'Offices'],
    faqs: [{ q: 'Can I view on my phone?', a: 'Yes, iOS and Android app included.' }],
    relatedSlugs: ['biometric-access-control', 'electric-fencing'],
    inStock: true, isVisible: true, order: 2,
  },
  {
    slug: 'remote-gate-system',
    name: 'Remote Swing & Slide Gate System',
    category: 'Gate Automation',
    shortDesc: 'Motorised gate automation with GSM remote control.',
    longDesc: 'Our gate automation systems motorise existing or new swing and slide gates with GSM phone-call activation.',
    price: 'From ₦220,000',
    priceNote: 'Single gate. Dual gate pricing on request.',
    image: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80'],
    features: ['GSM phone-call activation', 'App-based remote control', 'Battery backup', 'Intercom integration'],
    specs: [{ label: 'Max gate weight', value: '500 kg' }],
    useCases: ['Private residences', 'Estate entrance gates'],
    faqs: [{ q: 'Works during NEPA outage?', a: 'Yes, 8-12 hours battery backup.' }],
    relatedSlugs: ['biometric-access-control', 'video-intercom'],
    inStock: true, isVisible: true, order: 3,
  },
  {
    slug: 'smart-home-automation',
    name: 'Smart Home Automation',
    category: 'Smart Home',
    tag: 'New',
    shortDesc: 'Full home automation integrating lighting, climate, entertainment, and security.',
    longDesc: 'Transform your home into an intelligent living space with centralised app control.',
    price: 'From ₦500,000',
    priceNote: 'Starter package. Full-home quoted on survey.',
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1558002038-1055907df827?w=800&q=80'],
    features: ['Centralised app control', 'Smart lighting & scenes', 'Voice assistant integration', 'Energy monitoring'],
    specs: [{ label: 'Protocol', value: 'Zigbee, Z-Wave, Wi-Fi, Matter' }],
    useCases: ['Luxury residences', 'New build developments'],
    faqs: [{ q: 'Works without internet?', a: 'Yes, local control works offline.' }],
    relatedSlugs: ['solar-power-system', 'cctv-surveillance'],
    inStock: true, isVisible: true, order: 4,
  },
  {
    slug: 'electric-fencing',
    name: 'Electric Fencing & Perimeter Security',
    category: 'Electric Fencing',
    shortDesc: '10,000V deterrent perimeter systems with alarm integration.',
    longDesc: 'High-voltage deterrent perimeter with integrated alarm, zone monitoring, and remote alerts.',
    price: 'From ₦280,000',
    priceNote: 'Per 50-metre run, inclusive of energiser.',
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80'],
    features: ['10,000V deterrent shock', 'Zoned alarm integration', 'SMS & app alerts', 'Solar-powered option'],
    specs: [{ label: 'Voltage output', value: '10,000V (deterrent)' }],
    useCases: ['Residential estates', 'Industrial compounds'],
    faqs: [{ q: 'Is it dangerous?', a: 'No, painful but non-lethal deterrent.' }],
    relatedSlugs: ['cctv-surveillance', 'biometric-access-control'],
    inStock: true, isVisible: true, order: 5,
  },
  {
    slug: 'solar-power-system',
    name: 'Solar Power & Battery Backup System',
    category: 'Solar Power',
    tag: 'Best Value',
    shortDesc: 'Keep your security systems running 24/7 during grid outages.',
    longDesc: 'Tier 1 monocrystalline panels, lithium-iron phosphate batteries, and hybrid inverters.',
    price: 'From ₦900,000',
    priceNote: '5kW starter system. Sized after free energy audit.',
    image: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80'],
    features: ['Tier 1 monocrystalline panels', 'LiFePO4 batteries', 'Hybrid inverter', 'Remote monitoring app'],
    specs: [{ label: 'System sizes', value: '3kW – 20kW' }],
    useCases: ['Homes & estates', 'Offices', 'Industrial facilities'],
    faqs: [{ q: 'Payback period?', a: '3-5 years based on current tariffs.' }],
    relatedSlugs: ['cctv-surveillance', 'smart-home-automation'],
    inStock: true, isVisible: true, order: 6,
  },
  {
    slug: 'video-intercom',
    name: 'Video Door & Intercom System',
    category: 'Intercom Systems',
    shortDesc: 'See and speak with visitors before granting access — from anywhere.',
    longDesc: 'HD video door stations with mobile app call forwarding and gate release.',
    price: 'From ₦150,000',
    priceNote: 'Single door station + indoor monitor.',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80',
    gallery: ['https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&q=80'],
    features: ['HD video door station', 'Two-way audio & video', 'Mobile app call forwarding', 'Remote door/gate release'],
    specs: [{ label: 'Camera resolution', value: '2MP HD' }],
    useCases: ['Private residences', 'Apartment blocks', 'Office reception'],
    faqs: [{ q: 'Answer from phone when away?', a: 'Yes, push notification + remote unlock.' }],
    relatedSlugs: ['remote-gate-system', 'biometric-access-control'],
    inStock: true, isVisible: true, order: 7,
  },
];
